version: 1.0.1.{build}
configuration: Release
test: off # Tests are off, since appveyor box can't create GraphicsDevice
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    git submodule update --init --recursive

    build_all.bat
artifacts:
  - path: src/Myra/bin/MonoGame/Release/Myra.$(appveyor_build_version).nupkg
    name: Myra.nupkg

  - path: src/Myra/bin/Stride/Release/Myra.Stride.$(appveyor_build_version).nupkg
    name: Myra.Stride.nupkg
    
  - path: Myra.$(appveyor_build_version).zip
    name: ZipPackage
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: $(appveyor_build_version)
    auth_token:
      secure: nIpZ5N6iQIXVV8/kK/Y6BqY4KYD+y7HYdq+vTKv+LqZBbxHE9BuEgZAHGVDvmJKh
    artifact: ZipPackage
    draft: false
    prerelease: false
    
  - provider: NuGet	
    api_key:
      secure: o02Abc+1Pg/C7FVPnbCA9i4RIakmOUcKjMBBCHDCbEhS69b+N05mV0xBe0ne2/Y4
    artifact: /.*\.nupkg/